### ISSUE TITLE
AttributeError: module 'pendulum' has no attribute 'Interval'

### ISSUE THREAD

**Issue by idchlife** [dusktreader/flask-praetorian#119]
Hi! Thanks for the library! It's fantastic! Now there is an error, which version should I use to overcome it? It appeared not a while ago.

**Comment by dusktreader** [comment]
This issue popped up when the latest version of pendulum went out. The change wasn't reverse compatible. However, this should be fixed in the master branch today. I'm going to be deploying a new release of flask-praetorian with pinned dependencies on flask 1.0 and pendulum 2.0 in a few minutes.

**Comment by idchlife** [comment]
Thank you!

I will try later 0.4.4, right now using your rc version from pypi 😁
