### ISSUE TITLE
.roles_accepted() does not work well with users which has several roles

### ISSUE THREAD

**Issue by idchlife** [dusktreader/flask-praetorian#133]
I just added several prints to the source to demonstrate what's the problem:

![default](https://user-images.githubusercontent.com/4563032/40272894-74570544-5bbe-11e8-8a01-04ceb418f3b4.png)

Maybe better to use

   one of current roles in accepted_roles

instead of set.issubset?

or I do not understand some specific logic?

Thanks!

**Comment by dusktreader** [comment]
@idchlife Thanks for opening this issue! I will look into it

**Comment by dusktreader** [comment]
Addressed by PR #134 

@brunoasantos Thanks so much for the PR. I had a family emergency come up this week, and I haven't had a chance to look into this. It's awesome that someone else did!

@idchlife I will be rolling out a new release to pypi very soon

**Comment by idchlife** [comment]
thanks @dusktreader @brunoasantos !
