### ISSUE TITLE
Add custom payload to jwt

### ISSUE THREAD

**Issue by tobsnk** [dusktreader/flask-praetorian#138]
Hi,
is there a way to add a custom payload or field to the token?

**Comment by dusktreader** [comment]
No, that isn't currently supported.

It could probably be added, but I think there would need to be a compelling use-case and a strategy to avoid unnecessary bloat in the token.

Do you have some ideas?

**Comment by tobsnk** [comment]
In my current use-case I have an id that is strongly tied to a group of users and used to filter some resources. I didn't want to pass the id all the time with every request, when the auth token is already
passed anyway and provides the necessary security to avoid any modification. So I thought it would be convenient to issue my id inside the token and extract it when the user does something that requires it.

I currently solved this by adding an additional parameter to the init_app function of flask-praetorian. The parameter itself is a function that receives the User object. In this function I then return a dictionary with my custom fields (currently just my special id, which is part of the user). Then, when creating the token, I merge the two dictionaries (the original one and my custom one).

I wouldn't know how to prevent excessive bloat, but I would argue that this is something that is up to the consumer of flask-praetorian to take care of.

**Comment by dusktreader** [comment]
It sounds legitimate. If you have forked/patched, could you post a pull-request? I might go a different way, but I think this is functionality I want to support, so I'd like to start from something.

Thanks for the feedback!

**Comment by tobsnk** [comment]
Ok, cool. I guess I can get a pull-request ready by the end of the weekend.

Another possible solution I thought of might be by adding properties to the User model and also adding a special decorator to them, which then can be extracted by flask-praetorian. 
My python skills are still very rudimentary, so I'm not sure if that is easily possible, but it is another approach which seems to be a bit more close to how it currently works, at least from a consumer perspective.

**Comment by dusktreader** [comment]
This has been addressed by #140 
A new release of flask-praetorian will be out shortly that includes this change.
Thanks for your input and pull-request. I think this is a good feature, and I hope it helps folks out

**Comment by tobsnk** [comment]
Thanks for adding this so quickly. Great work!

**Comment by dusktreader** [comment]
You are very welcome! Thanks for the idea and use-cases!
