### ISSUE TITLE
Consider email-based registration mechanism

### ISSUE THREAD

**Issue by dusktreader** [dusktreader/flask-praetorian#141]
Creating new users is tricky for an api-based application. It would be nice to have a way to create a new user and provide verification via email.

I'm not sure this fits into flask-praetorian, but to be a complete batteries-included auth system it might be necessary.

Think about how something like this could be integrated

**Comment by pahrohfit** [comment]
Pull #145 submitted

**Comment by pahrohfit** [comment]
shouldn't work tired, implemented suggested fixes for this and verify_and_update into each others branches.  there are also some overlaps between the two.

I'm going to close both and submit a singular pull.

**Comment by dusktreader** [comment]
Oh, ok. I was going to just merge the verify_and_update branch since it looks like it was based on this one. A new PR is fine, too

**Comment by pahrohfit** [comment]
Yeah, i suck.  147 submitted.

Also found an issue in the unit tests, cleaned it up, and provided an example flask-restful endpoint for email registration stuff.

**Comment by dusktreader** [comment]
resolved by #147
