### ISSUE TITLE
How to init default user without app context

### ISSUE THREAD

**Issue by freenetwork** [dusktreader/flask-praetorian#173]
How to init default user without app context?

I want to:
python init_app.py

Then:
python app.py

**Comment by dusktreader** [comment]
I'm not sure what you are asking here.

The implementation of users is left the the user. The library just requires some methods to be defined on the User class. The user is bound in the app context for requests that come in on routes that are decorated with the `@praetorian.auth_required`

**Comment by freenetwork** [comment]
When I deploy, I want to create a user by default. That is, I do not have app context

**Comment by mkulava** [comment]
Why can't you initialise db connection in "init_app.py" and insert the user in the database?

**Comment by dusktreader** [comment]
flask-praetorian won't help you with that. Creation and updating users has to be handled by your application code. Even granting roles needs to be handled by your app code. flask-praetorian is just an auth package.

If you want to create a user without an application context, you cannot really do it with flask. You could execute SQL directly (or perhaps with alembic), but, I'm afraid, that's a problem that must be left to the user to solve

**Comment by freenetwork** [comment]
The examples indicate the creation of a password through your library. Eg need app context.
Question: can I specify a password for the user? Without your library

**Comment by dusktreader** [comment]
The app context is necessary for praetorian to function correctly when hashing passwords for storage in the data store.

However, you could use flask-cli to create an app context in a command-line context. https://flask.palletsprojects.com/en/1.1.x/cli/
