### ISSUE TITLE
Add support for account (password) resets

### ISSUE THREAD

**Issue by pahrohfit** [dusktreader/flask-praetorian#176]
Add an endpoint for performing password resets (lost password).

- send customized emails with instructions
- generate a token of new type `reset` for validation
- validate token expiration
- be tied to a unique user
- allow existing password to continue working, until such time as the reset directions are followed
- be one time use (link/token cannot be re-used)

To this end, 2 new functions would be added:

- `send_reset_email()` -- Generate a reset token based on `.identify()` property, craft an email from defined template, and send it (returning the details similar to `send_registration_email()`
- `validate_reset_token()` -- Take a provided token, perform necessary validations (not expired, valid user, active user, token is "current" for the user) and provide a status response for the developer to take whatever actions they desire.

**Comment by pahrohfit** [comment]
I've gotta fix/add docstrings, and will include some sample code.

**Comment by mukeshsharma1201** [comment]
This is exactly I was looking for! Thanks.
Just wanted to know when this PR will be merged.

**Comment by dusktreader** [comment]
This was addressed in pull-request #177

**Comment by 9192gks** [comment]
AttributeError: 'Praetorian' object has no attribute 'send_reset_email'
is the attribute send_reset_email in the praetorian object ?
