### ISSUE TITLE
Prepare new release for password reset and optional auth

### ISSUE THREAD

**Issue by dusktreader** [dusktreader/flask-praetorian#180]
Let's do a new release.
* Get optional auth decorator reviewed & merged
* Update changelog
* Tag & bag (deploy)

(this is mostly a note to self)

**Comment by AmitNeuhaus** [comment]
Hey ,
Really liked the package.
When there is gonna be an official Pypi release with the reset password functionality?
Thanks!

**Comment by dusktreader** [comment]
Sorry, life has been....pretty involved lately. I will try to get a new release out soon

**Comment by AmitNeuhaus** [comment]
Hey I am in a full time job right now, but if
any more help is needed in the future please let me know I will be pleased
to help if you have new features in mind!

**Comment by mukeshsharma1201** [comment]
Hi @dusktreader , Thank you for this amazing package.

I wished to use the password reset feature, so just wanted to check if the new release is coming soon?

**Comment by dusktreader** [comment]
@mukeshsharma1201 it's on my priority todo list. I've recently transferred into more of a management type role, and my spare time is really tight. However, I do intend to get the release out soon...hopefully within the week

**Comment by dusktreader** [comment]
My last comment has not aged well. I'm working on getting this release out. I have one or two more things to do including integration testing and applying some undocumented changes.

I apologize for things getting away; I promise you I haven't just been idle!

**Comment by dusktreader** [comment]
All the features have been merged and passed my ci/cd pipeline. My next step is to do some integration testing of the new features, and we should be good to release 1.1.0.

Thank you for your patience.

**Comment by mukeshsharma1201** [comment]
Thanks for the hard work @dusktreader !!  🙌

**Comment by dusktreader** [comment]
@mukeshsharma1201 @AmitNeuhaus Releasing 1.1.0 today (barring disaster)
