### ISSUE TITLE
gunicorn issue

### ISSUE THREAD

**Issue by mamude** [dusktreader/flask-praetorian#188]
Hi, I'm trying to discover the issue, but can't find a solution.

If I run 1 worker in Gunicorn, it's running fine, but when I've 3 or 5 workers, I receive this error for every request. Could you help me?

Best Regards,
Samir Mamude

Traceback (most recent call last):
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
user_1   |     rv = self.dispatch_request()
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
user_1   |     return self.view_functions[rule.endpoint](**req.view_args)
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
user_1   |     resp = resource(*args, **kwargs)
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
user_1   |     return self.dispatch_request(*args, **kwargs)
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
user_1   |     resp = meth(*args, **kwargs)
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask_praetorian/decorators.py", line 35, in wrapper
user_1   |     _verify_and_add_jwt()
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask_praetorian/decorators.py", line 23, in _verify_and_add_jwt
user_1   |     jwt_data = guard.extract_jwt_token(token)
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask_praetorian/base.py", line 466, in extract_jwt_token
user_1   |     options={'verify_exp': False},
user_1   |   File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
user_1   |     self.gen.throw(type, value, traceback)
user_1   |   File "/usr/local/lib/python3.7/site-packages/buzz/__init__.py", line 127, in handle_errors
user_1   |     raise cls(final_message).with_traceback(trace)
user_1   |   File "/usr/local/lib/python3.7/site-packages/buzz/__init__.py", line 111, in handle_errors
user_1   |     yield
user_1   |   File "/usr/local/lib/python3.7/site-packages/flask_praetorian/base.py", line 466, in extract_jwt_token
user_1   |     options={'verify_exp': False},
user_1   |   File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 92, in decode
user_1   |     jwt, key=key, algorithms=algorithms, options=options, **kwargs
user_1   |   File "/usr/local/lib/python3.7/site-packages/jwt/api_jws.py", line 156, in decode
user_1   |     key, algorithms)
user_1   |   File "/usr/local/lib/python3.7/site-packages/jwt/api_jws.py", line 223, in _verify_signature
user_1   |     raise InvalidSignatureError('Signature verification failed')
user_1   | flask_praetorian.exceptions.InvalidTokenHeader: failed to decode JWT token -- InvalidSignatureError: Signature verification failed (401)

**Comment by CJRChang** [comment]
Hello friend,

I run gunicorn+flask and I'm unable to replicate this issue while using multiple workers.
Based on the InvalidSignatureError, it suggests the JWT token being sent is invalid.

Can you confirm you're sending the right token or share a minimal project/config to replicate this?

**Comment by mamude** [comment]
Hello @CJRChang 

It was the SECRET_KEY, I was generating with os.urandom(8), that's the problem.

**Comment by dusktreader** [comment]
@mamude Sounds like the issue was resolved. Going to go ahead and close the issue
