### ISSUE TITLE
Refresh Token fails

### ISSUE THREAD

**Issue by balusmahendran** [dusktreader/flask-praetorian#190]
when I try to refresh a token I'm getting the error:

> { "error": "MissingUserError", "message": "Could not find the requested user", "status_code": 401 }

my settings on Lifespan are:

`app.config['JWT_ACCESS_LIFESPAN'] = {'minutes': 1}`
`app.config['JWT_REFRESH_LIFESPAN'] = {'days': 30}`

But, when I try to refresh the token within one minute, I'm correctly getting the Early Refresh Error:

> { "error": "EarlyRefreshError", "message": "access permission for token has not expired. may not refresh", "status_code": 401 }

I can access the protected route within one minute and beyond the access lifespan I'm correctly getting "access permission has expired" message.

Here is my route:

`@api.route('/refreshtoken', methods=['POST'])`
`def refreshtoken():`
	`req = request.get_json(force=True)`
	`old_token = req.get('token', None)`
	`new_token = guard.refresh_jwt_token(old_token)`
	`return jsonify({'fresh_token': new_token})`

I'm using Python 3.7.5, Flask 1.1.1 in Ubuntu 19.10

**Comment by balusmahendran** [comment]
It was error from my side!
In my User Model, I was having one more non-guessable user_id column which was exposed in token but didn't make it as Primary Key.
I back-tracked and found out that in my User model, cls.query.get(id) checks against Primary key only.

**Comment by chrismllr** [comment]
This is curious, I am also seeing the 
```
{ "error": "EarlyRefreshError", "message": "access permission for token has not expired. may not refresh", "status_code": 401 }
```
When trying to refresh a token 5 seconds before it expires. Is this intentional? I would like to build a "proactive" instead of "reactive" refresh functionality if possible.
