### ISSUE TITLE
Using Flask-Prateorian without username and password

### ISSUE THREAD

**Issue by elpapi42** [dusktreader/flask-praetorian#191]
Good Day!

I have a situation where my API access tokens are issued after an OAuth provider authenticate my users, so i really dont need protect my API with the integrated Flask-Praetorian username and password security. The problem is, the password and username are mandatory on the model that will be registered when initializing the plugin.

How can i dropout that feature?

Thanks in advance!

**Comment by dusktreader** [comment]
At this time, flask-praetorian is not really set up to be just a jwt broker in flask. It's not really set up to integrate with OAuth or another external security protocol. As it's intended to be a batteries-included security package, it's not likely that it will support use without some form of credentialed authentication.

My suggestion would be to either fork this repo and modify it for your use-case or just use pyjwt.

Thanks for your interest and idea, however.
