### ISSUE TITLE
pip-compile chokes on resolving dependencies

### ISSUE THREAD

**Issue by dodumosu** [dusktreader/flask-praetorian#192]
i'm not sure if it's because flask-praetorian uses poetry, but i have an existing project for which i'm using pip-tools to manage dependencies. when i added flask-praetorian to my dependencies.in and try to compile using `pip-compile --generate-hashes`, i get an error related to poetry, and i don't have it installed in my environment.

**Comment by dodumosu** [comment]
installing poetry solved the problem, but i think it's suboptimal to have two ways to manage dependencies

**Comment by dusktreader** [comment]
I'm sorry to hear this issue came up. I don't have the bandwidth right now to dig into it. I only intend to support pip for this particular package (and poetry, implicitly, of course)
