### ISSUE TITLE
Updates based on 3rd party review

### ISSUE THREAD

**Issue by dusktreader** [dusktreader/flask-praetorian#193]
A youtube video was posted giving a walk-through of how to use flask-praetorian. Listening to the author, I have a few fixes and improvements in mind:
* Call out required fields (from user) in example
* Possibly provide a mixin for required user properties
* Make roles support optional
* Work with author to clear confusion about password property
* Login from example should be a POST call
* Add some explanation of refreshing tokens in the docs

**Comment by mvhconsult** [comment]
It would be really helpful to document your example. At least more than now. What do you want to show in the files? What to look for in the examples.
How are the passwords passed and should the dev implement a Hashing method?

**Comment by dusktreader** [comment]
Resolved by pull request #215
