### ISSUE TITLE
User is inactive but still can access routes

### ISSUE THREAD

**Issue by ekbalba** [dusktreader/flask-praetorian#194]
I forced my user to be inactive using an update statement to the database. As long as I have the generated token for that user I can still access the routes even the user is inactive. 

Is there a way I can check if the user is inactive before accessing the routes?

**Comment by AmitNeuhaus** [comment]
Hey,
Im not the owner of the package , just using it.
I guess this is irrelevant anymore but might be useful for others.

Using JWT allows you to not query the database for every client request, in contrast what you are asking is to query the database every incoming request (with an already generated token) to check if the user is valid. 

The validity check that you are asking about occurs every request to **refresh** the token & every **login**.
So whenever you try to get a new refresh token there is a query to the database to see if there is a user and if it is valid (therefore you need a is_valid method in the USER class), if both are true a new access token is generated.

Security wise, thats the reason an access token has short lifespan.

**Comment by dusktreader** [comment]
I would also add that if you need to stop a user from accessing your api immediately, you should use the blacklist feature.
