### ISSUE TITLE
Py-buzz str format warning when making unauthorized request

### ISSUE THREAD

**Issue by phips-git** [dusktreader/flask-praetorian#197]
Hello,
first of all a big thanks for this great package, it works like a charm!
There is just a small issue I ran into, when testing unauthorized request to  an "auth_required" endpoint. The py-buzz dependency shows the following warning. Is there a possibility to suppress the warning until the new version is released?

![Screen Shot 2020-04-16 at 09 17 31](https://user-images.githubusercontent.com/44228158/79426224-1f60a880-7fc3-11ea-85d1-74bc75269ac8.png)

Thank you in advance!

**Comment by dusktreader** [comment]
@phips-git I think I can probably just fix this up pretty quick so it will be ready for the new release.

You would have to run python with warnings supressed to silence this until the next release is ready
