### ISSUE TITLE
Support for cookies.

### ISSUE THREAD

**Issue by AmitNeuhaus** [dusktreader/flask-praetorian#198]
Hey,
Im developing 3 react applications which have the same commom flask rest backend.
Each app is on another sub domain (app1.company.com, app2.company.com, login.company.com)

For now after i login with my login app i am having a jwt token that is recieved form backend but it cant be delivered to the other apps (localStorage is subdomain scoped). The only choice that i see is to use cookies to store the jwt which can be used cross sub domains.

I saw the decorators you are using for the routes are using the extract_from_header function but it seems to not support the cookie headers because of the regex in the match.
is htere another solution to my problem? what am i missing?
Thank you!

**Comment by eveninglily** [comment]
I'd also like to see a decorator for this! Here's some code for how I did this:
To set the token, for your login route or wherever you want to set it
```
resp = make_response("")
resp.set_cookie("token", value=token, httponly=True)
return resp
```
reading the token:
```
if 'token' not in request.cookies:
    return "no cookie", 401
token = request.cookies.get('token')
jwt_data = guard.extract_jwt_token(token)
add_jwt_data_to_app_context(jwt_data)
```

Not sure if this is the best way, and if the developer is interested in supporting this more officially, I could clean this up and make a PR

**Comment by AmitNeuhaus** [comment]
Nice ,
in jwt_extended it seems like there is a location config where you can pass a list of locations to check the token at.
the "extract_jwt_token" therefore go over all of them so the @auth_required suits every location, no more additional decorators are needed over there. maybe this is the approach that will suit in this package.

Anyways i moved to jwt_extended for the cookie case (support for csrf and so on...) but will try to contribute a PR for this package aswell.
Thanks mate.
