### ISSUE TITLE
API Documentation does not actually list any functions

### ISSUE THREAD

**Issue by eveninglily** [dusktreader/flask-praetorian#201]
On the [main page](https://flask-praetorian.readthedocs.io/en/latest/index.html), if you scroll down to the "API" section and click on it ([link here](https://flask-praetorian.readthedocs.io/en/latest/flask_praetorian.html)), it lists the modules, but not any of the actual functions or decorators.

**Comment by eveninglily** [comment]
Also, the Tutorial page (https://flask-praetorian.readthedocs.io/en/latest/tutorial.html) is pretty broken.

**Comment by mukeshsharma1201** [comment]
Thanks for this useful package!
And Yes, as a beginner I am finding it difficult to implement this library without the docs working properly. Hopefully someone good at Sphinx documentation raises a PR soon! 🤞

**Comment by dusktreader** [comment]
The tutorial is indeed broken. I've had a re-write of the tutorial as a full-fledged angular app in the works for a while, but just haven't gotten around to finishing it.

It's next on my personal todo list after getting the next release of flask-praetorian out

**Comment by dusktreader** [comment]
@McIntireEvan Also, I will make sure to get the api docs fixed up in the next release

**Comment by dusktreader** [comment]
Fixed in pull request #208
