### ISSUE TITLE
send_reset_email does not exist in Praetorian-Base.py

### ISSUE THREAD

**Issue by MattDJensen** [dusktreader/flask-praetorian#213]
Great project, very easy to implement. 

It seems that the send_reset_email you have outlined in your docs doesn't yet exist in the pypi package - 
Any timeline on this being pushed out? 

Specifically- This function:
send_reset_email(email, template=None, reset_sender=None, reset_uri=None, subject=None, override_access_lifespan=None)
from (https://flask-praetorian.readthedocs.io/en/latest/flask_praetorian.html?highlight=send%20reset%20password#flask_praetorian.base.Praetorian.send_reset_email)

Thanks!

**Comment by dusktreader** [comment]
This will be available in the next release.

I'm very sorry about the long, long, long delay. Changes to my personal life and a promotion at work have all but eliminated my ability to work on this project in my spare time. I hope to have the next release out soon, but I am not in a position to make promises.

Stay tuned, and thank you for being patient

**Comment by dusktreader** [comment]
@MattDJensen All the features have been merged and passed my ci/cd pipeline. My next step is to do some integration testing of the new features, and we should be good to release 1.1.0.

Thank you for your patience.

**Comment by dusktreader** [comment]
@MattDJensen Releasing today as long as things go smoothly
