### ISSUE TITLE
Please release new version with ability to fetch access token from cookie

### ISSUE THREAD

**Issue by Hubro** [dusktreader/flask-praetorian#214]
I accidentally read the documentation for "latest" rather than "stable", and I've been trying to figure out for the last few hours why the heck Praetorian insists on trying to fetch the access token from a header, even though I have configured it to only fetch it from cookie.

Turns out fetching the access token from a cookie has been implemented for months, but hasn't yet been released.

Storing the access token anywhere other than cookies is not an option in my current project due to XSS concerns, so it would be great if this change was released.

I would be happy to contribute if there is anything missing in order to release the changes.

**Comment by dusktreader** [comment]
I'm sorry this feature hasn't been released yet. About 6 months ago, I took on a new role at my job which basically eliminated any spare time there to work on personal projects. I am trying to get the 1.1.0 release ready to go, but it has been a process to find time to work on it. I have a few issues to work through and then should be able to push out the new release.

Stay tuned, and thank you for your patience

**Comment by dusktreader** [comment]
@Hubro All the features have been merged and passed my ci/cd pipeline. My next step is to do some integration testing of the new features, and we should be good to release 1.1.0.

Thank you for your patience.

**Comment by dusktreader** [comment]
@Hubro Releasing today (unless disaster happens)
