### ISSUE TITLE
Cannot init_app if models are defined elsewhere.

### ISSUE THREAD

**Issue by dillonhmayhew** [dusktreader/flask-praetorian#224]
In most cases a larger Flask API will not be in a single file. I have an application structured where my app is created, followed by Flask's signature import from the bottom of the file.

Flask Praetorian prevents me from initializing because it immediately assumes my model has no lookup class method.
```
flask_praetorian.exceptions.PraetorianError: The user_class must have a lookup class method:
user_class.lookup(<str>) -> <user instance> (401)
```

I have tried a few things like initializing it after my model defintion, but I can't do that either because it's out of context:
```
with current_app.app_context():
      guard.init_app(current_app)
```

I've also tried a few other nasty hacks, but the only solution I can see so far is restructuring my project so that the models are defined in the same file as I initialized my app.

If you have any ideas around this error, please let me know.

Thanks

**Comment by therealrobster** [comment]
I have my app separated into multiple files using the app factory pattern.  It works fine and I have many routes in many different files.  For example, user, customer, auth, etc.

I have an extensions.py where I do as such:

    from flask_mongoengine import MongoEngine
    from flask_praetorian import Praetorian
    from flask_mail import Mail

    db = MongoEngine()
    guard = Praetorian()
    mail = Mail()

My app.py is as such:

    from flask import Flask
    from .extensions import db, guard, mail
    from .models import User
    from .blueprints.customer import customerRoute
    from .blueprints.errors import errors_bp
    from .blueprints.users import usersRoute
    from .blueprints.auth import authRoute
    from .blueprints.admin import adminRoute


    def create_app():

        # instance_relative_config tells flask to look for an instance module that's in the same folder depth as the main module
        app = Flask(__name__, instance_relative_config=True)

        # look for a settings.py file in the config folder
        app.config.from_object('config.settings')

        # routes
        app.register_blueprint(customerRoute)
        app.register_blueprint(errors_bp)
        app.register_blueprint(usersRoute)
        app.register_blueprint(authRoute)
        app.register_blueprint(adminRoute)

        # extensions
        extensions(app)

        return app

    def extensions(app):
        db.init_app(app)
        guard.init_app(app, User)
        mail.init_app(app)
        
        return None

Then my blueprints are in their own folders and operate like so:

    from flask import jsonify, Blueprint, request, redirect, render_template
    from flask_api.extensions import db, guard
    from flask_api.models import User
    from flask_api.errors import bad_request, error_response

    authRoute = Blueprint('auth', __name__)

    # LOG IN
    @authRoute.route("/login", methods=["POST"])
    def login():
        # Logs a user in by parsing a POST request containing user credentials and issuing a JWT token as a response.
        data = request.get_json(force=True)
        username = data.get("email", None)  #using email for username.  flask_praetorian restriction on using username over email
        password = data.get("password", None)

        user = guard.authenticate(username, password)
        ret = {"access_token": guard.encode_jwt_token(user)}
        
        return (jsonify(ret), 200)

I hope that helps a little

**Comment by dillonhmayhew** [comment]
I am the worst. I forgot to pass `User` as a parameter 😞 

Thank you for your response though, it did point me to looked where I had missed
