### ISSUE TITLE
AttributeError: 'Praetorian' object has no attribute 'hash_password'

### ISSUE THREAD

**Issue by tego101** [dusktreader/flask-praetorian#225]
`nm.hashed_password = r.get('password', None)`

Extension just started showing this error after restarting it. Not sure where is coming from.

**Comment by dusktreader** [comment]
Could you please provide a stack trace and some code context?

**Comment by tego101** [comment]
Sorry totally my fault.

AttributeError: 'Praetorian' object has no attribute 'hash_password'

**Comment by dusktreader** [comment]
I haven't seen this issue arising in my own usage before. So, to figure out why it might be happening, I need to see a stack trace if possible so I can see where the error is originating. If you could supply some code around the area where you are making the failing function call, that would also help.
