### ISSUE TITLE
send_reset_email. How are people adding your custom email templates?

### ISSUE THREAD

**Issue by therealrobster** [dusktreader/flask-praetorian#227]
I'm just checking in to see how you're sending your email template for the verification.

I have it working and sending the default verification email which is fine.  I've created a HTML template now though and want to use it instead.

Following the docs it says to do as so:

    send_reset_email(email, template=None, reset_sender=None, reset_uri=None, subject=None, override_access_lifespan=None)

so I did:

    guard.send_registration_email(user.username, user=user, template="path.to.template.html")

Stupid me, the email came in, with `path.to.template.html` in the body.  So I get that.  String.

I've tried to somehow get it to the path of the file like so:

    .flask_api/blueprints/auth/templates/new_registration_email.html

...however I get a `500 INTERNAL SERVER ERROR` with `"details": "'str' object has no attribute 'new_registration_email'"`.

I can't imagine I have to put the complete html in the send_registration_email and I can't find anything in the docs, so I'm a little stumped.

How are you adding your HTML template in this case?

Any advice greatly appreciated.  Thank you

**Comment by mukeshsharma1201** [comment]
Have you tried using `guard.send_registration_email(user.username, user=user, template="new_registration_email")` and placing `new_registration_email.html` in `templates` folder?

**Comment by therealrobster** [comment]
@mukeshsharma1201 thank you for your suggestion.

I just tried:

    guard.send_reset_email(user.email, subject="Password Reset Request", template="reset_password")

I have a template in my `templates` folder called `reset_password.html`.

However, the email does send and it simply comes through with `reset_password` as a string in the body of the email.  That's it.

I tried without string (no " " around `reset_password`) like so:

    guard.send_reset_email(user.email, subject="Password Reset Request", template=reset_password)

and the send fails.

I am setting my templates up like I always do like so:

    authRoute = Blueprint('auth', __name__, template_folder='templates')

In the past the templates have always worked when rendering them to the browser.  I'm just a little stumped.  There's got to be something I'm missing. Is there a global setting for flask-praetorian that I might be missing perhaps?

**Comment by Skanyi** [comment]
This is how I'm using custom email template. 
Assuming you have a template in your `templates` folder called `reset_password.html`
```
# Read the template info
with open('templates/reset_password.html') as res_template:
    reset_template = res_template.read()
```
Then when sending an email
```
reset_response = guard.send_reset_email(
    email, 
    reset_sender=sender,
    template=reset_template, 
)
```
 Hope that helps you get going.

**Comment by therealrobster** [comment]
So sorry I'm late to this reply.  I will definitely try this and am keen to see how it goes!
