### ISSUE TITLE
User can create unlimited refresh tokens off an expired token.

### ISSUE THREAD

**Issue by tego101** [dusktreader/flask-praetorian#229]
Ok so `guard.refresh_jwt_token(old_tkn)` does its job. If before exp time return EarlyRefresh Exception. But if the token is expired I can continuously use the expired token to obtain a new token.

**Comment by jbhoorasingh** [comment]
The JWT_REFRESH_LIFESPAN value is used to determine how long a expired token can be used to obtain a new valid token.

Has this timeframe elapsed?

**Comment by dusktreader** [comment]
Each new token produced from refreshing the token:
1. Has the same refresh lifespan as the original, so you can't refresh indefinitely. Once the original token's refresh lifespan is used up, all of the tokens created by refreshing it also have no refresh lifespan remaining.
2. Has the same payload, including the jti claim, as the original. the only difference is that the expiration lifespan is renewed.
3. Cannot be refreshed once the refresh lifespan expires.
