### ISSUE TITLE
Decorators don't read token from cookies

### ISSUE THREAD

**Issue by natalieh235** [dusktreader/flask-praetorian#231]
auth decorators only try reading a token from the header, not cookies

**Comment by jital94** [comment]
the issue is with decorator. In decorators.py guard.read_token_from_header() instead of guard.read_token()

`def _verify_and_add_jwt(optional=False):
    """
    This helper method just checks and adds jwt data to the app context.
    If optional is False and the header is missing the token, just returns.

    Will not add jwt data if it is already present.

    Only use in this module
    """
    if not app_context_has_jwt_data():
        guard = current_guard()
        try:
            token = guard.read_token_from_header()
        except MissingToken as err:
            if optional:
                return
            raise err
        jwt_data = guard.extract_jwt_token(token)
        add_jwt_data_to_app_context(jwt_data)
`

**Comment by mohan78** [comment]
@jital94 is there any workaround for this issue?
