### ISSUE TITLE
pyjwt version dependency outdated

### ISSUE THREAD

**Issue by sammck** [dusktreader/flask-praetorian#233]
As currently published in pip, this package forces pyjwt < 2.0. This breaks current versions of other packages, such as flask-jwt-extended 4.1.0 which requires pyjwt >= 2.0.  The current version of pyjwt is 2.0.1. Any plan to update dependencies?

**Comment by sammck** [comment]
I think I can see that this is necessary if you intend to support python 3.4/3.5 which are at end-of-life.. I also noticed that you don't list Python 3.8 as compatible... looks like I'm out of luck.  Thanks...

**Comment by dusktreader** [comment]
As soon as my tests pass, I should be able to merge and publish. Thanks for pointing this out!

https://github.com/dusktreader/flask-praetorian/pull/240

**Comment by dusktreader** [comment]
flask-praetorian 1.2.0 has just been released. this updates the dependency on pyjwt ^2.0.0
