### ISSUE TITLE
Extended Algorithm Support?

### ISSUE THREAD

**Issue by ToddKingham** [dusktreader/flask-praetorian#249]
Does the library currently support RS256 tokens? I would like to integrate into existing application that is using asymmetric key signing. I need to be able to use the existing Public/Private keys.

**Comment by dusktreader** [comment]
One of the core flask-praetorian dependencies is pyjwt, and it does support RS256. However, flask-praetorian assumes that you will be using a symmetric encryption algorithm and only has a single key that it uses for encoding and decoding the token. Adding support for asymmetric encryption could potentially be a future feature (if there is demand for it), but it isn't currently supported
