### ISSUE TITLE
Flask 2.0 Support

### ISSUE THREAD

**Issue by dsposito-ubtech** [dusktreader/flask-praetorian#250]
Hello, Flask 2.0 was recently released however I'm unable to upgrade my application due to praetorian requiring flask <2.0: https://github.com/dusktreader/flask-praetorian/blob/master/poetry.lock#L196

I'm not familiar with Poetry - but it seems like it's `flask-buzz` that has the <2.0 requirement for flask?

If you can help confirm whether a change needs to be made to buzz and/or praetorian then I'm happy to help from there.

Thanks!

**Comment by dusktreader** [comment]
Oh, great call out. Both flask-buzz and flask-praetorian will need to be updated. I will try to get to this soon.

**Comment by vaustrup** [comment]
Hi, I would be interested in using this with Flask 2.0 as well. Just to get an idea, do you have a rough estimate for the timeline? Of course, I'd also be happy to help, if needed.

**Comment by dusktreader** [comment]
I am swamped with work right now. Trying to make some progress on the other major issue/pull-request. Timeline would probably be later this summer. Pull requests are welcome

**Comment by dsposito-ubtech** [comment]
@dusktreader It looks like @kreyoo has a PR (linked above) to resolve this.

**Can we prioritize the review of this PR? It'll really help unblock this issue from the past several months.**

Let me know if I can help in any way.

**Comment by jvllmr** [comment]
@dusktreader Please remember that [#29](https://github.com/dusktreader/flask-buzz/pull/29) from flask-buzz also has to be merged because flask-buzz for this to work.
