### ISSUE TITLE
Error when registering: JWT token not found in headers under 'Authorization'

### ISSUE THREAD

**Issue by mariopnvds** [dusktreader/flask-praetorian#254]
I have been following the [register](https://github.com/dusktreader/flask-praetorian/blob/master/example/register.py) example. When registering a new user, the email is sent and received but when clicking on the email button with the url containing the token (http://localhost:5000/finalize?token={long_token}) it redirects me to a new page on the browser with the following error: 
{
  "error": "MissingToken", 
  "message": "JWT token not found in headers under 'Authorization'", 
  "status_code": 401
}

It seems that it does not get the token from the url. As I have mentioned before, I have just copied the code to test it.

Any help?
Thank you in advance!

**Comment by Erikmmkarlsson** [comment]
You should change the URI to a page on the frontend, (you do this with a parameter in the send_email function). Make a page that reads the url parameter and then sends it to the api with the correct jwt authentication.

**Comment by Erikmmkarlsson** [comment]
Here's how I did it in react: https://www.github.com/Erikmmkarlsson/graphmaster/tree/master/src%2Fcomponents%2Flogin%2FFinalize.jsx

**Comment by mariopnvds** [comment]
Thank you very much!
