### ISSUE TITLE
Make role decorators accept Enums.

### ISSUE THREAD

**Issue by jvllmr** [dusktreader/flask-praetorian#257]
It could be very useful if you can use string enums instead of strings for e.g. the roles_required decorator:

```
from enum import Enum

class RoleEnum(str, Enum):
    ADMIN = "admin"
    MANAGER = "manager"

@app.route("/admin")
@roles_required(RoleEnum.ADMIN)
def test():
    return "Admin stuff"
```

**Comment by dusktreader** [comment]
This would be an interesting approach but I think it would add more constraints to the "user" object that I want to avoid.

**Comment by jvllmr** [comment]
It wouldn't as far as I know. With the implementation mentioned above the decorator converts the enum into the value behind it, converted to a string. This way the requirements to the User object stay the same.
