### ISSUE TITLE
why the dict has not attribut password

### ISSUE THREAD

**Issue by SuyogSoti** [dusktreader/flask-praetorian#258]
TypeError: hash must be unicode or bytes, not propert

```python

    @classmethod
    def lookup(cls, username):
        user = mongo.db.users.find_one({"username": username})
        user["_id"] = ""
        print(type(user))
        print(user)
        return User().from_dict(user)
```

**Comment by dusktreader** [comment]
This is a result of the way that your mongodb engine is implemented. None of the code provided above uses anything implemented in flask-praetorian.

Sorry I couldn't be of more help; I'm not a mongodb user and only added an example provided by another contributor to help folks who are.
