### ISSUE TITLE
Anti-Brute-Force

### ISSUE THREAD

**Issue by jvllmr** [dusktreader/flask-praetorian#261]
Disabling access to an IP after a some failed password attempts would be great. You could enable the feature by passing the needed database model into the module initialization method.

**Comment by dusktreader** [comment]
The problem with implementing this is that it would require flask-praetorian to include some sort of memory store to count failed attempts related to a specific ID. It should be fairly straightforward for the client code to do this using a memory store implemented in the app code.

I feel like this would be outside the scope of flask-praetorian and add further constraints or assumptions as to the facilities available in the app.
