### ISSUE TITLE
`PRAETORIAN_RESET_SENDER` might be an optional configure argument?

### ISSUE THREAD

**Issue by imoyao** [dusktreader/flask-praetorian#273]
https://github.com/dusktreader/flask-praetorian/blob/c23d10e0d6e34b2b3102b9b71e48f006b8397467/flask_praetorian/base.py#L243
```python
    self.reset_sender = app.config.get(
        "PRAETORIAN_RESET_SENDER",
    )
```
might can be replace by:
```
...
DEFAULT_SENDER = app.config.get(
                "DEFAULT_SENDER"
            )
...
    self.reset_sender = app.config.get(
        "PRAETORIAN_RESET_SENDER",
        DEFAULT_SENDER 
    )
```
IPO,the only `DEFAULT_SENDER` can meet the needs of sending mail. If the application need to use different mail sender, they can further set them separately?

**Comment by dusktreader** [comment]
It's a good thought! I'll look into it when I have some cycles to work on praetorian.

**Comment by dusktreader** [comment]
Decided not to implement this. There are only sender settings. It's trivial to use one value for both settings in your app's implementation.
