### ISSUE TITLE
raise `Could not fetch an id from the registration token`

### ISSUE THREAD

**Issue by imoyao** [dusktreader/flask-praetorian#274]
What if i invoke `db.session.commit()` after `send_registration_email()` ?

here is the example codes:
```python
def register():
    """
    Registers a new user by parsing a POST request containing new user info and
    dispatching an email with a registration token
    .. example::
       $ curl http://localhost:5000/register -X POST \
         -d '{
           "username":"Brandt", \
           "password":"herlifewasinyourhands" \
           "email":"brandt@biglebowski.com"
         }'
    """
    logger = flask.current_app.logger
    req = flask.request.get_json(force=True)
    username = req.get("username", None)
    email = req.get("email", None)
    password = req.get("password", None)
    logger.debug("Processing register request for:")
    logger.debug(f"  {username}")
    logger.debug(f"  {password}")
    logger.debug(f"  {email}")
    new_user = User(
        username=username,
        password=guard.hash_password(password),
        roles="operator",
    )
    db.session.add(new_user)
    db.session.commit()
    try:
        guard.send_registration_email(email, user=new_user)
    except Exception as err:
        logger.error(f"Couldn't send registration email: {err}")
        raise
    ret = {
        "message": "successfully sent registration email to user {}".format(
            new_user.username
        )
    }
    return flask.jsonify(ret)
```
In my practice, I think we should ensure that the system sends a confirmation email successfully before creating a user,so i changed the code like this(This code is not working, but you will know what I mean):
```python
...
new_user = User(
        username=username,
        password=guard.hash_password(password),
        roles="operator",
    )
    db.session.add(new_user)   # not commit() here

    try:
        guard.send_registration_email(email, user=new_user)
    except Exception as err:
        logger.error(f"Couldn't send registration email: {err}")
        db.session.rollback()
        raise err
    # if send mail successfully, i will invoke `db.session.commit()`,otherwise,i will invoke `db.session.rollback()`
    db.session.commit()
```
here is the related code:
https://github.com/dusktreader/flask-praetorian/blob/c23d10e0d6e34b2b3102b9b71e48f006b8397467/flask_praetorian/base.py#L447
```python
...
payload_parts = {
        "iat": moment.int_timestamp,
        "exp": access_expiration,
        "jti": str(uuid.uuid4()),
        "id": user.identity,  # here and the next line will get None
        "rls": ",".join(user.rolenames),
        REFRESH_EXPIRATION_CLAIM: refresh_expiration,
    }
... 
```
Is this a wrong practice?Do I have to write user information really to the database before I can send mail?

**Comment by dusktreader** [comment]
There's a problem with atomicity here. For example, if you wait to commit until the email is sent, what happens if the commit fails? Now you have an invited user that you don't have a record of. In your database you could have a status column to indicate if the email was sent or not and then take action on those for whom sending the email failed.

Ultimately, we try to keep flask-praetorian agnostic of the data store backend, so the implementation details with managing database transactions is dependent on implementation.

However, you will need a user identifier in the token for the registration to work correctly.

**Comment by imoyao** [comment]
Thank you for your reply,as you said:
>  we need a user identifier in the token for the registration to work correctly.

It's intelligent that “ have a status column to indicate if the email was sent or not”.😃
