### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by antarestrader** [dusktreader/flask-praetorian#288]
In all examples `guard.init_app(...)` is run outside of application context. This warning should be made safe to call without `flask.current_app` or examples should be updated to call guard.init_app(...) with an app context.

This bug will only be encountered when the user_class requires one or more parameters to get an instance.

https://github.com/dusktreader/flask-praetorian/blob/32e614e0cd1374b3519144fbefe8e09f6162c813/flask_praetorian/base.py#L321

**Comment by dusktreader** [comment]
This is a pretty simple fix. Doing some cleanup work while I'm at it. Should have a new release ready soon.

**Comment by dusktreader** [comment]
This has been fixed and should work fine in flask-praetorian v.1.5.0.
