### ISSUE TITLE
Add verify_and_update support

### ISSUE THREAD

**Issue by dusktreader** [dusktreader/flask-praetorian#43]
We will need the ability to verify a password using it's encryption algorithm and then re-encrypt with a new algorithm. This is necessary if an application decides to switch encryption methods but still needs current passwords to function correctly.

**Comment by pahrohfit** [comment]
You mean via it’s hashing algo, yeah?

**Comment by dusktreader** [comment]
@pahrohfit yes

**Comment by pahrohfit** [comment]
Pull coming in for this tomorrow

**Comment by pahrohfit** [comment]
Pull #146 submitted.

**Comment by dusktreader** [comment]
resolved by #147
