### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.project_metadata.json'

### ISSUE THREAD

**Issue by marlonchalegre** [dusktreader/flask-praetorian#47]
After executing pip install:

 File "/tmp/pip-build-79fz6d8x/flask-praetorian/setup.py", line 7, in <module>
    with open('.project_metadata.json') as meta_file:
        FileNotFoundError: [Errno 2] No such file or directory: '.project_metadata.json'

**Comment by dusktreader** [comment]
@Psicodelico Apparently, I didn't get my MANIFEST.in checked in. I'll get a new version pushed out ASAP

**Comment by dusktreader** [comment]
@Psicodelico should be resolved by PR #48 

Please try to pip install again and let me know if it works for you

**Comment by marlonchalegre** [comment]
That was fast :). It's working now, thank you.
